{
 "title": "histogram buckets",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Success/Failure",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "graphql_resolver_millisecond4_count{service=\"graphql\",result=\"error\"}",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "graphql_resolver_millisecond4_count{service=\"graphql\",result=\"success\"}",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Heatmap of Duration Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (rate(graphql_resolver_millisecond4_bucket{service=\"graphql\", result=\"success\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Duration Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (rate(graphql_resolver_millisecond4_bucket{service=\"graphql\", result=\"success\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rate of errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(graphql_resolver_millisecond4_count{result=\"error\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}