name: Go Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

# make sure we only have 1 instance of test workflow
# run per pull request.
concurrency:
  group: go-test-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  test:
    uses: TempMee/x/.github/workflows/go-test-template.yaml@main
    secrets:
      TEMPMEE_CI_APP_ID: ${{ secrets.TEMPMEE_CI_APP_ID }}
      TEMPMEE_CI_PRIVATE_KEY: ${{ secrets.TEMPMEE_CI_PRIVATE_KEY }}
      SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  release:
    name: semantic-release
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.2
            @semantic-release/changelog@6.0.1
