name: go-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: 1.22

jobs:
  build:
    name: go-tests
    runs-on: ubuntu-latest
    steps:
      - name: generate tempmee-ci access token
        uses: tibdex/github-app-token@v1.8.0
        id: generate_ci_token
        with:
          app_id: ${{ secrets.TEMPMEE_CI_APP_ID }}
          private_key: ${{ secrets.TEMPMEE_CI_PRIVATE_KEY }}

      - name: configure git with tempmee-ci access token
        env:
          CI_TOKEN: ${{ steps.generate_ci_token.outputs.token }}
        run: |
          git config --global url."https://tempmee:${CI_TOKEN}@github.com".insteadOf "https://github.com"

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: mocks
        run: make generate

      - name: Setup go modules
        run: go clean -modcache;go mod tidy; go mod download; go mod verify;

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout=5m --modules-download-mode=readonly
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Test and generate code coverage
        run: go test -v -race --tags=integration_test -coverprofile=coverage.txt -covermode=atomic ./...
